# Generated by Django 4.2.7 on 2023-12-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AplikasiLayananUMKM', '0003_telatela_rename_harga_aishtea__harga_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AyamGeprek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_menu', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gambar', models.ImageField(null=True, upload_to='img/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Esteh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_menu', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gambar', models.ImageField(null=True, upload_to='img/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NasiKuning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_menu', models.CharField(max_length=255)),
                ('deskripsi', models.TextField()),
                ('_harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gambar', models.ImageField(null=True, upload_to='img/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
